###
# @name createAsset

POST http://localhost:3000/assets
Content-Type: application/json

{
  "name": "Seles Force",
  "symbol": "CRM",
  "price": 200,
  "image": "CRM.png"
}

###
@assetId = {{ createAsset.response.body._id }}

###
GET http://localhost:3000/assets

###
GET http://localhost:3000/assets/AMZN

###
# @name createWallet
POST http://localhost:3000/wallets

###
@walletId = {{ createWallet.response.body._id }}

###
GET http://localhost:3000/wallets

###
GET http://localhost:3000/wallets/9f0c997f-cd6d-4be7-8760-97e6c6bbe9f0


###
POST http://localhost:3000/wallets/{{ walletId }}/assets
Content-Type: application/json

{
  "assetId": "{{ assetId }}",
  "shares": 1850
}

###
POST  http://localhost:3000/orders
Content-Type: application/json

{
  "walletId": "{{ walletId }}",
  "assetId": "{{ assetId}}",
  "shares": 40,
  "price": 300,
  "type": "BUY",
  "status": "PENDING"
}

###
GET  http://localhost:3000/orders?walletId={{ walletId }}